// Generated by CoffeeScript 1.6.3
var $cur_exp, $exp, $flag, $input, $match, $visual_pre, anchor, anchor_c, delay, delay_id, delay_run_match, entityMap, escape_exp, escape_html, init, run_match, select_all_text;

$exp = $('#exp');

$cur_exp = $('#cur_exp');

$input = $('#input');

$match = $('#match');

$visual_pre = $('#visual-pre');

$flag = $('#flag');

init = function() {
  $input.keyup(delay_run_match);
  $exp.keyup(delay_run_match);
  $flag.keyup(delay_run_match);
  $('[save]').each(function() {
    var $this, v;
    $this = $(this);
    v = localStorage.getItem($this.attr('id'));
    if (v !== null) {
      return $this.val(v);
    }
  });
  run_match();
  $cur_exp.click(select_all_text);
  $('[title]').tooltip();
  return $exp.select();
};

delay = $('#exe_delay').change(function() {
  return delay = $(this).val();
}).val();

$('.switch_hide').click(function() {
  var $tar, $this;
  $this = $(this);
  $tar = $('#' + $this.attr('target'));
  if ($this.prop('checked')) {
    return $tar.hide();
  } else {
    return $tar.show();
  }
});

delay_id = null;

delay_run_match = function() {
  clearTimeout(delay_id);
  return delay_id = setTimeout(run_match, delay);
};

anchor_c = 0;

anchor = function(title) {
  var c;
  c = anchor_c++ % 4;
  switch (c) {
    case 0:
      return "<i title='" + title + "'>";
    case 1:
      return "</i>";
    case 2:
      return "<b title='" + title + "'>";
    case 3:
      return "</b>";
  }
};

entityMap = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;"
};

escape_exp = /[&<>]/g;

escape_html = function(str) {
  return String(str).replace(escape_exp, function(s) {
    return entityMap[s];
  });
};

select_all_text = function(containerid) {
  var range;
  if (document.selection) {
    range = document.body.createTextRange();
    range.moveToElementText(this);
    return range.select();
  } else if (window.getSelection) {
    range = document.createRange();
    range.selectNode(this);
    return window.getSelection().addRange(range);
  }
};

run_match = function() {
  var count, cur_exp, e, exp, flag, i, input, j, k, list, m, r, visual, _i, _len;
  exp = $exp.val();
  flag = $flag.val();
  input = $input.val();
  if (!exp) {
    $match.text('');
    $cur_exp.html('');
    return;
  }
  try {
    r = new RegExp(exp, flag);
  } catch (_error) {
    e = _error;
    $match.text(e);
    return;
  }
  cur_exp = r.source;
  cur_exp = cur_exp.replace(/\\\//g, '/').replace(/\//g, '\\/');
  cur_exp = RegexColorizer.colorizeText(cur_exp);
  $cur_exp.html('/' + cur_exp + '/' + flag);
  m = input.match(r);
  list = '<ol start="0">';
  if (m) {
    for (_i = 0, _len = m.length; _i < _len; _i++) {
      i = m[_i];
      list += "<li>" + i + "</li>";
    }
  }
  list += '</ol>';
  $match.html(list);
  $match.append("JSON: <pre>" + (JSON.stringify(m)) + "</pre>");
  visual = '';
  count = 0;
  if (r.global) {
    i = 0;
    while ((m = r.exec(input)) !== null) {
      k = r.lastIndex;
      j = k - m[0].length;
      visual += escape_html(input.slice(i, j)) + anchor(count++);
      visual += input.slice(j, k) + anchor();
      i = k;
      if (m[0].length === 0) {
        r.lastIndex++;
      }
    }
    visual += escape_html(input.slice(i));
  } else {
    visual = input.replace(r, function(m) {
      return m = anchor() + m + anchor();
    });
  }
  $visual_pre.empty().html(visual);
  return $visual_pre.find('[title]').tooltip();
};

window.onbeforeunload = function() {
  $('[save]').each(function() {
    var $this;
    $this = $(this);
    return localStorage.setItem($this.attr('id'), $this.val());
  });
  return null;
};

init();
